packages:
  # all packages in subdirs of components/
  - 'projects/**'
  # exclude packages that are inside demo directory
  - '!projects/demo/**'

# doesn't work with ng-packagr
catalog:
  '@angular/common': ^21.2.0
  '@angular/core': ^21.2.0
  tslib: ^2.3.0
