name: Create and publish ngx-oauth2-access-token

on:
  release:
    types: [published]

jobs:
  build-and-release-package:
    if: ${{ startsWith(github.event.release.tag_name, 'ngx-oauth2-access-token_v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependcies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: npx ng build @mrpachara/ngx-oauth2-access-token -c production
      - name: Publish package
        working-directory: ./dist/mrpachara/ngx-oauth2-access-token
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@${{github.actor}}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
          ls
          cat .npmrc
          npm publish
