name: Create and publish ngx-oauth2-access-token

on:
  release:
    types: [published]

jobs:
  build-and-release-package:
    if: ${{ github.event.release.tag_name }} =~ ^ngx-oauth2-access-token/release/v[0-9]+\.[0-9]+\.[0-9]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PACKAGE_SCOPE: mrpachara
      PACKAGE_NAME: ngx-oauth2-access-token
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com
      - name: Install dependcies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: |
          npx ng build @$PACKAGE_SCOPE/$PACKAGE_NAME -c production
          cp LICENSE ./dist/$PACKAGE_SCOPE/$PACKAGE_NAME
      - name: Publish package
        working-directory: ./dist/${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
